name: Deploy Telegram Bot

on:
  push:
    branches:
      - main # Автоматически срабатывает при пушах в главную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          load: true
          outputs:
            type: local
            dest: output

      - name: Run Docker Container
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} # Передача токена через переменную окружения
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }} # Передача токена через переменную окружения
        run: |
          docker run --rm -e TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN} my-bot-image